### ISSUE TITLE
Question about the gene identifer in dataset.

### ISSUE THREAD

**Issue by SejeongPark8354** [JieZheng-ShanghaiTech/KG4SL#2]
Hi, I have a question about the train_data_final_1_1~5.csv you uploaded.
I want to change the gene idenfier into gene name, but I couldn't find the file for this.
I think the id in dbid2name.csv is not aligned with this. Also, I tried to apply sl_complete.csv in SynLethDB for this, but I couldn't. 
Can you help me solve this?

**Comment by shikew** [comment]
Hi,

Thanks for your interest. 

You can try the [reindexid2geneName](https://github.com/JieZheng-ShanghaiTech/KG4SL/blob/main/src/train.py#L10C1-L10C1) function defined in src/train.py to convert gene identifiers into gene names. 
  
The function first uses entity2id.txt to map the gene identifiers to corresponding database IDs. Then, it uses dbid2name.csv to map these database IDs to the actual gene names.

Regarding the sl_complete.csv in SynLethDB, please note that since SynLethDB has been updated, the IDs in this database may have changed. You can find more discussion [here](https://github.com/JieZheng-ShanghaiTech/KG4SL/issues/1) .

**Comment by SejeongPark8354** [comment]
Good! I'll try the function you said. 
Thanks you for your fast response.
